### ISSUE TITLE
Error occurred while enabling DatapackLoader v1.3.0 (Is it up to date?)

### ISSUE THREAD

**Issue by supernova4420** [lichenaut/DatapackLoader#7]
Running papermc 1.20.6 in a docker environment.

Datapackloader.jar placed in plugins folder and the following error is seen in the console:

>....
[10:51:31 INFO]: [DatapackLoader] Enabling DatapackLoader v1.3.0
>....
[10:51:31 ERROR]: Error occurred while enabling DatapackLoader v1.3.0 (Is it up to date?)
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: 'plugins/DatapackLoader/datapacks/dungeons-and-taverns-3.2.jar'
	at org.apache.commons.io.FileUtils.requireDirectory(FileUtils.java:2736) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.requireDirectoryExists(FileUtils.java:2752) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:2186) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:334) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1188) ~[commons-io-2.15.1.jar:2.15.1]
	at DatapackLoader.jar/com.lichenaut.datapackloader.urlimport.DLDatapackFinder.fileWalk(DLDatapackFinder.java:87) ~[DatapackLoader.jar:?]
	at DatapackLoader.jar/com.lichenaut.datapackloader.DatapackLoader.onEnable(DatapackLoader.java:83) ~[DatapackLoader.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
>....
[10:51:31 INFO]: [DatapackLoader] Disabling DatapackLoader v1.3.0

no other errors, server starts fine just without datapacks

**Comment by supernova4420** [comment]
Discovered that datapacks on modrinth tagged for fabric or forge do not work for paper. The version tagged 'datapack' worked perfectly.
